---
title: 读《中国通史》有感
author: LJJ
date: '2020-06-27'
slug: 历史中的那些事
cover: /img/读中国通史有感.jpg
images:
  - /img/读中国通史有感.jpg
categories:
  - 历史
tags:
  - 历史
highlight: no
---

历史虽是记录事实之书，但吾辈之探求，则为理而非事。理是概括众事的，事则是只是一事。天下事没有两件真正相同的，执应付此事的方法，以应付彼事，自然要失败。根据于包含众事之理，以应付诸事，则不至于此了。然而理是因事而见的，舍事而求理，无有是处。所以我们求学，不能不顾事实，亦不能死记事实。

中国虽然有三皇五帝的传说，但是目前没有任何的文字记载，中国正确而又不断的记载，起于周朝厉王、宣王两朝的共和元年，这在世界各国已经很早了（来源吕思勉先生的中国通史）。进入东周后，诸侯强大，王廷衰败，通过战争而出现春秋五霸，共计242年。战国259年，诸子百家，文化思想繁荣，改革兴起，变法图强，先有魏文侯任用吴起等贤臣，夺秦国河西之地。后楚悼王用吴起变法，南平百越，北并陈、蔡，却三晋，西伐秦，称雄于一时。秦孝公任用商鞅变法，以法家思想促进秦国发展，终秦始皇奋六世之余烈，吞二周而亡诸侯。自前230年至前221年，秦始皇嬴政派遣王翦、王贲等将领先后灭韩国、赵国、魏国、楚国、燕国、齐国这六国，结束于了战国时代。

秦朝历二世而亡，后又陷入争斗，刘邦虽无领兵之才，外有韩信、张良、萧何和陈平等人，内有吕后守成，虽多败但一战而定天下。经文景而治，国家平稳，然汉武帝穷兵黩武，军事力量强大，考虑民生不足。至汉宣帝时代，汉朝经济达到繁荣（吕思勉先生对汉武帝评价很低，奇怪）。汉宣帝后，汉朝开始走下坡路，王莽篡汉，并实施诸多意想不到的改革政策，使得外有匈奴作乱，内有绿林、赤眉，刘秀重用河北诸将，经过多年征伐，终统一天下，出现“光武中兴”，然而后汉到了第四任帝王，出现羌乱，而外戚和宦官专权开始出现。经过桓灵二弟，东汉实力大减，后来董卓实际上已经篡汉，自此开始进入三国，基本上也是多战乱。后司马炎统一中国，开始出现政治清明，可能是祖先太聪明，出现了“何不食肉糜”的憨皇帝，后来五胡乱华，基本上是中华文化的倒退，东晋之后，进入南北朝，北朝北魏分裂，东魏与西魏，南朝宋齐梁陈也是多战乱。经历了百年的战乱，杨坚一统中国，但是又一个二世而亡（隋炀帝和崇祯的评价都是褒贬不一），天下又是进入战争阶段，李世民通过外交、军事等手段平定刘黑闼、王世充、窦建德等等大小军阀，李建成又平定山东，到了李世民时代，重用李绩、李世绩、李道宗、薛万彻等等名将（唐朝名将真的多！）对外征战，平定东西突厥和西北西南，内重用长孙无忌、房玄龄、杜如晦、魏征等人，开创贞观之治。唐玄宗除去政敌韦皇后、太平公主等人，开创“开元盛世”。经过多代人的努力，唐朝一度繁荣，甚至高仙芝在西北和罗马还干过一战，但是一次安史之乱就使得唐朝实力大不如前，人口锐减，可想而知战争的后果多严重。唐朝皇帝也是瞎操作，杀名将，防重臣；叛军也是操作猛如虎，在战争的紧要关头，安禄山、史思明都被自己的儿子杀害了，后来淮南叛乱，所以叛军投降，唐朝立马就同意了，但虽然天下平定，基本上中央能够管控的地方有限了，节度使的力量太大。到了唐宣宗，组建15万的神策军，南征北战，实现了唐朝又一次繁荣，但是后来神策军腐败，宦官当道，没过多久，黄巢起义，从广东一直打到北方，在朱温、李克用等人的努力下，唐朝又延续了几十年，但是此时国家基本又陷入战乱，朱温、李克用等节度使也是多战役，抢夺地盘（最苦的还是底层人民哎）！

进入五代十国，基本上节度使的格局，五代十国：梁唐晋汉周加几个小国又让中华陷入水深火热之中，正如钱穆先生所说：五代十国是中国最黑暗的时代之一，这一段历史是真的乱，民不聊生。终于等到赵匡胤陈桥兵变，登上皇帝宝座，平定天下，可惜山西太原一直攻克不下，在没有完成大统一的时候就神奇去世，而北宋多守成之君臣，始终始终也没有实现大统一，但是经济文化繁荣，人口财富增加，人民生活至少相比之前富裕。王安石变法想增强国力，也最终失败，但王安石变法仍然有重要的影响。封建社会多乱世，合久必分，经过靖康之耻之后，南宋最多也只能偏安一隅，只能算是一方诸侯了，灭亡也是时间问题，终于忽必烈同一中国，实现几百年来未有的大一统，但是元朝帝王更替太频繁，相比清朝的帝王传承差远了，百年历史。匆匆已过，农民皇帝自南方起军，一直打到北方，经过徐达、蓝玉等人的北伐，基本平定天下，进入了历史上又一个盛世：明朝初期皇帝多创业之君，自英宗之后就是守成之君。在民生凋敝，军备疲弛的情况下，张居正除去政敌，任用循吏，终于使得缺钱的明王朝有了1000多万两的真金白银，但是10几年的改革随着张居正的死去而消亡（改革守下去真是艰难），明朝到了崇祯
，完全是个烂摊子。辽东的皇太极，西北南方的流寇，中原地区的连续大旱，官员腐败，军事、经济和政治都无法挽救，财政赤字过于严重，天灾人祸，崇祯皇帝再厉害也无法扭转乾坤了。

清朝入关后，吸取历代王朝经验，无论是君王的传承、对其它民族的方针、对人民的管理等，都比很多王朝做的好。历代都是前几代是创业之君，到了后边就是守成之君，清朝也不例外，自从嘉庆之后，道光、咸丰、同治等等都是守成之君，到了咸丰时代，内外都无法管控，后边就沉迷酒色，英年早逝。从1840年国门被迫打开后，第一次鸦片战争、第二次鸦片战争、中法之战、太平天国运动、义和团运动、甲午中日战争（1895），20世纪初，八国联军侵华，十月革命、巴黎和会失败等等，1930年中原大战，蒋系、桂系、晋系、西北争夺地盘，最终蒋介石战胜，加上张学良东北易帜，蒋介石成为中国的实际领导人。1931九一八事变，张学良退出关东，1937年日本全面侵华，国民党正面战场20多次大的会战，有利的阻击了日军的袭击，敌后战场也在断日军的补给线发挥重要作用，1945年日军投降。1946年又开始内战，一打又是三年。建国后各种原因，出现大跃进、三年自然灾害、文革，并且与美国、苏联、印度、越南等国家彰显国家主权，1978年改革开放后，以经济改革为中心，先富带动后富（这段历史温铁军教授的八次危机和去依附更详细），但是又出现资产阶级自由化，思想混乱，容易被误导，在1992年南方谈话后，各地开始真正进入改革，没有思想包袱，并且后边无论是军事经济文化思想都没有出现历史上的大问题。

从1978年到现在，也才40年时间，从1992年南方谈话，没有争乱开始，经济发展也才30年左右，能够实现目前的繁荣已经很了不起，很多弊端、诸多现象是发展过程的一种结果，需要改革，需要进步，但不可太快，华夏5000年的历史有诸多经验，也犯了好多错，这些历史都是巨大的财富。事事不同但理相同，没有两片相同的叶子，也没有两件一样的事情，也没有一样的改革，有的只是站在今年，汲取过去的经验，不断发展。比如温铁军教授提出的债务泡沫、金融泡沫、地产泡沫这三个难兄难弟是捆在一起的，这个会慢慢改革，除去弊端，中国改革才40年，取得成绩举世瞩目。像美国、日本、英国等国家，最短的改革也有100年历史了，所以看历史，让人更加清醒！

> 读吕思勉先生《中国通史》有感而发






































