---
title: 对编程软件学习的看法和理解
author: LJJ
date: '2020-07-16'
slug: 对编程软件学习的看法和理解
cover: /img/对编程软件学习的看法和理解.jpg
images:
  - /img/对编程软件学习的看法和理解.jpg
categories:
  - R学习
tags:
  - R学习
highlight: no
---

之前看苏姗教授的论文（计量经济学大家），提到学生的编程能力比10年前要求更高，现在看发表的论文确实能感受到这一点，此外，朋友圈的**python**广告也将python吵得快一飞冲天了，然而说实话并没什么管用哈哈。现在我也发现，腾讯那么有钱，为啥就不能营造个干净的环境，有时候真的吐槽，国内这么大的市场，好好做软件不好吗，非得加这么多广告，这点和推特和YouTube真的差的太远（貌似没有可比性，经常看国外教授的个人主页，**论文+code+github+推特**一般是标配，国内就是项目资金名头......当然这个环境也不是一时能够改变的，毕竟国内有博士点也才几十年的时间，慢慢来吧）

在学术这块，或者是求学的阶段，**编程+写作+数学英语**是标配，一篇论文，也是由这些组成的：读优秀的英文论文，用数学知识理解内在逻辑，然后通过编程处理数据模拟，形成实证结果，最后通过写作发表论文。整个流程就这样，从这个过程中可以发现：三者都很重要，所以目前我的主要落脚点也在这几个方面,今天先谈**编程**这件事情。

作为曾经数学系的证明狗，真的对数学无感，没什么兴趣，也不知道数学这玩意到底干啥，（现在入门经济学，鬼知道经济学是干啥的？经世济民？醒醒吧，国内有几个人是经济学家？以文学家为例，胡适，鲁迅，梁漱溟...这些人称的上“家”，国内很多经济学家也就是学者而已，甚至还不是学者），不过现在感觉数学和英语是最好的工具，无论是学术还是工作，只要是脑力劳动，这两个缺一不可，只不过很多人没有体会到而已，或者有人将英文翻译过来，比如林语堂先生的著作。尤其是博士或者是技术性工作，数学和英语真的很重要！！！（咋又扯远了）

编程这玩意，主要看你想干啥，杀鸡焉用牛刀。算个1 + 1用个计算器不就可以了，非得弄得这么高大上嘛，来个编程软件，打开然后敲击命令，你要是用windows打开**MATLAB**，黄花菜都凉了。或者非得用程序来个生日歌：

````
happy = function() cat("Happy birthday to you\n")
sing = function(person) {
    happy()
    happy()
    cat(paste("Happy birthday dear", person, "\n"))
    happy()
}
sing("you")
````

````
Happy birthday to you
Happy birthday to you
Happy birthday dear you
Happy birthday to you
````

借用谢益辉评论这个代码的话：

> 这不仅仅是一个浪漫的函数，也深刻反映了程序员的基本素质：抽象与模块化。此时，有些看官可能心里长叹，在程序世界征战代码半辈子，还不如人家一首生日歌。

所以干什么事用什么工具，工具服务于我们，而不是陷入工具的深渊里（当然，有些工具真的有用，比如看视频**PotPlayer**，**谷歌学术**，**Rmarkdown等**，我上课**宣传**了好多软件，这些人或者企业真应该给我打钱哈哈）。简单介绍社科类我曾经用过的软件（菜鸟目前主要用R，stata和python，上课讲的学术系列，工作，可视化和Markdown系列等等也是基于此，当然**git、 github和blogdown**结合也很爽-又该给我打钱了）。

- **MATLAB**：本科参加五次数学建模用的都是（没换队友，编程主力是一位女生，汗颜哈哈，所以考研结束就去学R了，招聘会上介绍R给人的感觉很不错，没想到一入坑就两年多，坑坑）MATLAB，当然我有点打杂，不写作，不怎么写代码（谁让这个女生编程太秀了，我提95%的要求她都能实现），MATLAB很强大，但是吧，数据分析用R更适合，MATLAB更加适合量化建模等等
- **spss**：这玩意吧，有点简单，队友编程，我也不能拉下，就用spss点点，出来一些结果：比如ARIMA模型，这是我大二就会用但是不懂的模型哈哈。当初自己好菜，现在属于菜鸟二级（当年是一级吧，或者没有品级）
- **eviews**：处理时间序列的神器，有很多时间序列模型，现在主要用的是时候翻翻高铁梅老师的书和张晓彤老师的课件
- **stata**：这个是微观数据处理的有用工具，但是很多最新模型更新太慢，除了计量外界用的少，身边朋友统计的用R、python和SAS的居多。现在主要上课演示用，以R之优秀攻击stata之弊端（原谅我，虽然stata也很好用，我关注的推特几个教授都是R和stata的大佬，写了很多R包）
- **python**:朋友圈和很多公众号都有推荐python课程，鄙人曾经学过一个月，现在忘得差不多了，只会用rstudio跑几行代码而已，但是python也蛮好用的，尤其是深度学习这一块。但是但是！很多人被他的配置环境会搞蒙，就好像java配置环境一样，虽然有annoconda，但是tab键不好用（有着老年痴呆的我，没有tab键，好多参数都要help，而help界面不好看，我就一顿操作改了R.css文件，现在赏心悦目了）。
- **R**：我对R语言是真爱，所以需要放到最后啦啦。重要的事情必须最后说嘛:对于**计量**，R可以，我写了一系列教程；对于**机器学习**，caret和tidymodel，前者我还翻译了中文文档；对于**金融财务**，最近开发了tidy...包（老年痴呆症犯了，忘了）；对于**可视化**，ggplot2及其系列拓展包；对于**时间序列分析**，蔡瑞雄的时间序列分析，包括2019年又出了一本新书哈，这位大佬的书刷一遍，混个硕士毕业没问题，还能看看大佬是怎么写书的；对于**沟通交流**，blogdown写博客，比如此篇，bookdown写书，pagedown写分页html等等，谢益辉的包真的都很好用；**数据处理**，tidyverse一系列包（tidyverse是对R的美容，Rmarkdown系列是R开疆拓土的产品）；对于**shiny**，那也是神奇的神器呀，不过国内用的少；对于**爬虫**，简单的R也可以，深入的还是转战python吧，你想再“深入”，监狱之门向你招手哈哈；对于**统计分析**，R里边实现的算法比其他软件更新更快，这也是开源的好处吧。呱唧呱唧我说了好多，总之一句话，学会R，会用excel，做个学术不成问题，找工作，等等吧，除非你是开发中的大佬，专门会一门软件，也可以找工作，除非你是开发了python、Julia类似的编程软件的大佬哈哈。

说了这么多，可能有人会怼我，这就是萝卜白菜各有所爱，你爱白菜我爱萝卜（就好像情人眼里出西施，他人眼里是东施），各有选择，将自己的思维注入工具，得出自己自以为是的结论就OK，管他是怎么来的，你用手算ols也可以，只是好的工具能够解决问题，顺便提高效率就可以，我看论文，写作，上课等等吧，**感谢tidyverse和Rmarkdown系列工具**哈哈。

说了很多废话，再说点即将成为废话的实话：编程软件学习，先看视频，入门后看书，在做笔记，闲时翻翻自己的笔记哈哈。一门软件从入门到半个精通，至少两个月，在这个过程中多问多思考，敲代码多了，处理数据的时候再思考对应的函数就欧克了。要想精通，还是需要时间的，比如南方医科大的Y叔，那样的水平需要时间的积累，哈尔滨商业大学的阿信老师，复旦大学的黄天元（如果脑子没记错），这些人都是国内R语言的的大佬，如果你对R感兴趣，在工作之余，科研之外，就可以学习学习R，你可能会说，有病吧，没事看看剧不好吗，出去旅游不爽吗？当然好呀！我也喜欢旅游，每年出去溜达溜达，看剧也很好，比如我喜欢《黑冰》、《天道》、《贞观之治》和《大明王朝1566》等等，主要是培养一两个兴趣，学术很枯燥，工作很无聊，一两个兴趣可以解放自己。看剧、旅游、写作和学习R都可以嘛，根据自己的需求，只是表达自己的idea，仅此而已：有自己的兴趣爱好。

介绍一本好用的R书，也是我主讲的一本书《R数据科学》，这本书刷两遍，解决日常生活80%的数据处理没问题，如果你还想统计知识，那书就很多了，基础的比如《统计学基于R》，《R实战第二版》也不错，但是里边统计知识不适合初学者，由于篇幅省了太多东西。如果对**写作**感兴趣，可以读读谢益辉的书，如果对**版本控制**感兴趣，看看珍妮和哈德里的书等等，如果喜欢R语言，就当成排解压力的一种方式，如果不是，会用R做学术就可以了。

至于**如何研究学术**，先简单介绍，有机会再细说：先看书入门，知道这个东西是何物，看中文硕博论文，了解学者是怎么用的，用到那些领域，看中文论文，知道国内怎么应用的，看英文论文，明白那些国外大佬是怎么学术的，此外，学会科学上网，国外很多优秀的课程，就连字幕也可以翻译成中文，甚至有的还有字幕文档，不是吐槽学术环境和教学质量，相比较而言，我学习能力的提高（大四之前没有品级）和知识的学习，很大来源于github，YouTube和推特，上边很多优秀的资料。我逃过很多课，基本去刷别的课，之前看一门R语言的课，我自己就学了快一个月，课程量太大。不呱唧呱唧了，作为小白，路还有很长，年轻最大的资本是时间，越往后，越发现时间的重要性。生活不易，人生无常，分母-生命的长度无法控制（喝口水都会呛死），但是分子自己可以掌握，开心至上，有则多享受，少则少玩乐！

>写作很好，可以专注，可以回头看看当初的自己（不用当年了，毕竟自己看似还很年轻哈哈），是多么的傻，傻，还是傻！

```{r,echo=FALSE}
bubblyr::bubbly(theme = "rladies")
```





