---
title: 基金频繁上热搜真的好吗
author: Li Junjie
date: '2021-01-09'
slug: 基金频繁上热搜真的好吗
categories:
  - 学习
tags:
  - 学习
cover: /img/基金频繁上热搜真的好吗.jpg
images:
  - /img/基金频繁上热搜真的好吗.jpg
---

基金最近频繁上热搜，真的不是什么好事，总感觉有点“故意”的感觉，明明风险已经这么高了，还有这么高的热度。基金主要分为货币型基金，债券型基金，股票型基金和混合型基金，还有些QDII，指数基金等等。余额宝，零钱通背后都是货币型基金，风险最低，其他的都有一定的风险。目前只谈收益不谈风险的基金投资就是耍流氓。尤其是股票型基金和混合型基金，风险很高，但是收益很好，主要是因为最近行情太好了，大部分的权益类型产品给投资者带来了极大的回报。但是这也让基金逐渐上热搜，基金饭圈化，牛逼的基金经理人也有了无数的粉丝，但是当面临大跌的时候，又被骂的很惨！

比如某个人买了基金，7天内收取1.5%的手续费，万一感觉这一周涨了，不懂规则的小白立马卖了，发现可能扣除手续费玩了个寂寞。而且短期的大量赎回又会让基金经理人不得不卖出股票，影响基金经理人的操作，间接损害了所有持有人的利益，所以持有基金最怕的就是杀跌赎回。如果相信一个基金经理人，那么就持有多年，不断定投，总会有个好的结果，或者做个股债均衡配置，动态调整，间接的做到高抛低吸。

最近真的涨的很高了，沪深300已经屡次创新高，感觉这真的不是入场的好时机。中国才30多年的资本市场，就是个刚成长的小孩子，熊长牛短的格局短时间是破不了的，牛市应该是卖的时候，熊市应该是投资的时候，一轮周期7年左右，年化15%不是问题，但是大部分人总想赚快钱，那就要多学习，培养良好的心态，要不然，赚钱不是因为你厉害，而是行情就是这样。去年疫情初的时候，没有人喊牛市，但是现在普遍都感觉是牛市，那么这个时候就是最危险的时候。大家具有一致性的时候，风险也就很大了。

2000-2001的科技泡沫，2007-2008年的金融危机，2014-2015的股灾，不知不觉已经2021年，而这场牛市从沪深300的图像走势来看，已经2年了！！！而现在的走势还是“抱团走势”，非常像上世纪70年代的“漂亮50”的走势。根据历史规律，春节前后上涨的概率大约是80%，今年不知道，市场永远不可预测，不过大概率还是“抱团走势”，强者恒强，毕竟这么多募集的基金只能继续抱团，小市值公司根本入不了基金公司的眼，机构的股票池（类似于基民的基金经理人池）一般也不会考虑没有成长性的小市值公司。

随着疫情的平稳，全世界都会加息，收缩流动性，一旦货币政策发生变化（不急转弯不代表不转弯），那么下跌趋势也就来临，一旦形成“一致性”的恐慌，那就很可怕，半个月跌50%完全可能。

一旦下跌，两周就可能吃掉去年的整体收益。毕竟涨100%，跌50%就够了！

10000 * (1 + 1) * (1 - 0.5) = 10000

在基金投资中，减少波动性，做好组合，均衡配置是最重要的！涨20%，跌10%，我还是有8%的收益率，基本也就是“固收+”的收益了。

10000 * (1 + 0.2) * (1 - 0.1) = 10800

投资理财，首要的目的不是赚钱，而是跑赢通胀，然后是M2，最后才是获取超额收益。只要是最近两年买基金的，基本上做好均衡配置的，都赚得不少，而这很大程度上不是你赚钱了，而是放的水多了而已，看看鸡蛋，猪肉，蔬菜，涨的也不少了。

一点感想，写下自己的思路，未来(天知道有多远)基金还可能涨，但是跌的可能性也很大，一旦跌，感觉这一次会很可怕。

```{js, echo=FALSE}
$('.title').css('color', 'red')
$('.title').css('font-family', 'Times New Roman')
```

```{css, echo=FALSE}
* {
    # font-size: 17px !important;
    font-family: "Times New Roman" !important;
    # color: rgb(0 0	0)
}
::selection {
   # background: rgb(135 206 255);
}
```

```{css, echo=FALSE}
h2 {
    font-size: 21px !important;
    font-family: "Times New Roman" !important;
    color: rgb(	255 140 0)
}
h1 {
    font-size: 24px !important;
    font-family: "Times New Roman" !important;
    color: rgb(	255 0 0)
}
::selection {
   # background: rgb(135 206 255);
}
```

```{r,echo=FALSE}
library(bubblyr)
bubblyr::bubbly(theme = "warmup")
# bubblyr::bubbly(theme = "rladies")
```


























