---
title: 阅读《价值》——张磊
author: Li Junjie
date: '2021-01-09'
slug: 阅读-价值-张磊
categories:
  - 读书
tags:
  - 读书
cover: /img/读《价值》笔记.jpg
images:
  - /img/读《价值》笔记.jpg
---

# 序言

人生的每一次选择都是一次重要的价值判断，而每一次判断都来源于人们的底层信念。在社会、经济、科技、人文迅速发展变化的当下，对机会主义和风口主义尤要警惕。长期主义不仅仅是一种方法论，更是一种价值观。流水不争先，争的是滔滔不绝。从事任何工作和事业，只要着眼于长远，躬耕于价值，就一定能够经受时间的考验，找到迎接挑战的端绪。

真正的投资，有且只有一条标准，**那就是是否在创造真正的价值**，这个价值是否有益于社会的整体繁荣。坚持了这个标准，时间和社会一定会给予奖励，而且往往是持续、巨大的奖励。

每个人都可以成为自己的价值投资人，时间、精力、追求和信念，这无数种选择，都是对自己人生的投资。价值创造无关高下，康庄大道尽是通途。以赤子之心，不被嘈杂浇铸；出走半生，归来仍是少年。希望在坚持长期主义的旅途中，与你们同行，做时间的朋友。

# 价值的底色

## 我的知识大树

## 人生第一次操盘

## 从五矿到五湖四海

**读书、思考、实践**，对这个世界的好奇和探索，使我在很小的时候就明白，追求事业和梦想，必须对自己有所承诺，着眼于长远，全神贯注并全力以赴。在不同的际遇中，学习所有能学习到的最高标准，从而获得理解与洞察的能力，这是我一直以来坚持的长期主义。

- 构建属于自己的知识体系和思维框架，是塑造投资能力的起点。
- 在快速变化的市场中寻得洞见，不仅需要掌握金融理论和商业规律，还要全面回顾历史的曲折演进，通晓时事的来龙去脉，更要洞悉人们的内心诉求。
- 价值投资不是数学或推理，不能纸上谈兵，必须像社会学的田野调查一样，理解真实的生产生活场景，才能真正掌握什么样的产品是消费者所需要的、什么样的服务真正有意义。
- 人生中很重要的一件事是，找一帮你喜欢的、真正靠谱的人，一起做有意思的事。

# 价值投资启蒙

时刻让自己保持开放是最重要的学习心态。无论是普世的智慧、基础的原理，还是独到的见解，我都甘之如饴。

## 现代历史交集之地纽黑文

## 偏执带来的不断碰壁

一个人的职业生涯很长，不能做任何对帮助过你的人有损害的事情，否则那可能会困扰你的一生。

## 初识大卫·史文森

## 走近耶鲁捐赠基金

# 价值投资初试炼

## 孕育和新生

## "老友记"开张

## "中国号快车"，请立即上车

## 大行情中的"特立独行"

## 基因决定了非如此不可

# 价值投资方法与哲学    

## 从持续20年的零售业研究谈起

## 研究驱动

价值投资最重要的标志就是**研究驱动**。对于一家专注于研究行业、研究基本面的投资公司，核心能力就是对商业本质的敏锐洞察。在高瓴刚创办的时候，我们就要求每一位研究人员都应该尽力成为一些行业的专家，而且是独立的专家，把行业的来龙去脉看清楚。因为最好的分析方法未必是使用**估值理论**、**资产定价模型**、**投资组合策略**，而是坚持第一性原理，即追本溯源，这个“源”包括基本的公理、处世的哲学、人类的本性、万物的规律。

## 理解时间的价值

杰夫·贝佐斯问沃伦·巴菲特：“既然赚钱真像你说的那么简单，长期价值投资永远排在第一位，那么请问为什么有那么多人赚不到钱？”巴菲特回答：“**因为人们不愿意慢慢赚钱**。”许多人想赚取快钱，希望能够快进快出，但这种打法恰恰忽视了复利的价值。当一家一流的企业源源不断地创造价值，并被投资人选中时，复利就是时间赠予这笔投资最好的礼物。

在复利的数学公式中，本金和收益率还只是乘数，而**时间是指数**。这意味着，伴随着时间的拉长，复利效应会越发明显。一旦认识到时间的价值，就不会在意一时的成败，因为时间创造的复利价值，不但能让你**积累财富**，还能让你在实现价值的过程中**获取内心的宁静**。

需要补充的是，**时间创造复利的价值并不意味着一定要长期持有**，长期持有是有前提的，即好的企业能够随着时间不断创造新的价值。所以，我们希望更多的投资能够成为时间的朋友，并希望长期持有它们。

对时间的理解，第三个角度是**把时间作为选择**。很多时候，成功不在于你做了什么，而在于你没有做什么。把时间分配给能够带来价值的事情，复利才会发生作用。投资中最贵的不是钱，而是时间。做投资非常重要的是时间管理，把时间投入到怎样的问题上和怎样的人身上，是决定投资能否成功的基础性因素。 

新学的东西会在过去所学基础上产生积累和超越，知识会出现复合式的增长。所以，用这种方式做投资，时间越长，结果会越好。**知识和能力的积累，如果以复合式增长且速度较快**，会促成投资复利增长的加速。同样，如果稍有不慎，一项严重的错误也会把所有的积累都化为乌有，这也是时间的残酷性。正是基于这些认识，我们才坚持慢慢来，不去在意一时的快意恩仇，避开账面的、短暂的浮动价值，而是慎重选择并尽力追求可积累、可展望的胜利成果。

## 世界上只有一条护城河

## 投资的生态模型

## 从发现价值到创造价值

价值投资的理念已经**从早期关注市净率发展到关注企业真正的“内在价值”阶段**，从“寻找市场低估”发展到“合理估值、稳定成长”，可以说是价值投资理念的完善和丰富。这种投资理念的进化也是与美国20世纪80年代的发展相匹配的。

## 坚守三个投资哲学

- 守正用奇
- 弱水三千，但取一瓢：一定要克制住不愿意错失任何好事的强烈愿望，同时又必须找到属于自己的机会。
- 桃李不言，下自成蹊：不要在意短期创造的社会声誉或者价值，而应在意的是长期创造了多少价值。

坚持要“找靠谱的人一起做有意思的事”，在投资的过程中就会充满与相知相识的人共同征服挑战的愉悦感和成就感，这样就能实现“不言”或者“少言”。

在价值投资的路上，有深山大泽，亦有宜人坦途；有迷途知返，亦有绝处逢生。坚持投资哲学并非僵化，而是以严谨的治学精神去认识市场，提炼出最基本的价值观。在经济压力巨大的时候，作为一名投资人，最糟糕的事情就是恐慌。但当我们把事情想清楚了，自然能够保持内心的宁静，享受过程，知行合一。而塑造内心的宁静，归根结底就是做事情有目标、有原则、有行动指南和反馈机制，在不同的处境面前有定力，这就需要我们做出的每一步选择都是心安之选。

价值投资最伟大之处在于，它将“投资”这项难以确定的事情变成了一项“功到必成”的事业，变成逻辑上的智识和拆解，数字里的洞见和哲学，变化中的感知和顿悟。**“唯有诗人能扩张宇宙，发现通向新真理的捷径”**，我们在长期主义之路中探求本质，在未来和此刻间搭建通途。

- 最好的分析方法未必是使用估值理论、资产定价模型、投资组合策略，而是坚持第一性原理，即**追本溯源**，这个“源”包括基本的公理、处世的哲学、人类的本性、万物的规律。
- 独立研究的最大价值是让投资人敢于面对质疑，坚信自己的判断，敢于投重注、下重仓。
- 世界上只有一条护城河，就是企业家们不断创新，不断地**疯狂地创造长期价值**。
- 商业竞争本质上要看格局，要看价值，要升维思考，从更大的框架、更广阔的视角去看给消费者创造怎样的价值。
- 对于投资人来说，看人就是在做最大的风控，这比财务上的风控更加重要，只要把人选对了，风险自然就小了。
- 如果说价值投资的出发点是发现价值的话，其落脚点应该是创造价值。
- 所谓长期结构性价值投资，是相对于周期性思维和机会主义而言的，核心是反套利、反投机、反零和游戏、反博弈思维。
- 在多数人都醉心于“即时满足”的世界里时，懂得“延迟满足”道理的人，已经先胜一筹了。

# 价值投资者的自我修养

就像许多人“懂得很多道理但依然过不好一生”一样，投资当中也有许多道理被反复提及，但许多人在应用时仍然不解其意。比如“当别人害怕时，你要贪婪；当别人贪婪时，你要害怕”、“价格是你付出的，而价值才是你得到的”、“利润只是一种意见，而现金流却是一个事实”、“你只有买得便宜，才会卖得便宜”、“永远不要把买入成本当作卖出的决策依据”……

## 坚持第一性原理

要想在一生中获得投资成功，并不需要顶级的智商、超凡的商业头脑或内幕消息，而是需要一个稳妥的知识体系作为决策基础，并且有能力控制自己的情绪，使其不会对这种体系造成侵蚀。 

第一性原理的最大价值在于两点，其一是能够看清楚事物的本质，其二是能够在理解本质的基础上自由地创新。 

**投资界一个重要的分水岭**不在于区分个人投资者和机构投资者，而在于**区分有能力进行高质量积极投资管理的投资者和无力为之的投资者**。高质量的积极管理，其关键是思维模式。在我的理解和实践中，第一性原理不是简化分析模型，而是探究更底层的逻辑，发现“看不见的手”，找到各种现象的动因，进而分析更多端绪和因果。

高级商业物种之所以能适应环境，**其根本在于能够为社会持续不断地创造长期价值**，让消费者获益。想研究清楚商业物种的属性，需要长期跟踪商业历史。尽管历史是无比宏大的，任何人都无法在宏观世界里搞清楚所有问题，但人能够在时空的进化中，看清楚一些商业的基本问题。需要注意的是，**人们永远无法掌握真理，只能无限接近真理**，真理对于人们来说是高维的、复杂的、不可知的，但驱动事物变化的原因往往是简单的、单一的、可判断的，因此就需要从现象出发，抓住可以把握的关键要素。

## 强调理性的好奇、诚实与独立

理性意味着拒绝短期诱惑、功利心和许多天然的人性弱点，同时意味着拒绝主观臆断，以怀疑的态度、科学的方法去提出问题并找到答案。 

第一，好奇心一定源自**原创性的头脑**，可以打破所有条条框框的约束。好奇心的本质是自我驱动力，是一种朴素的求知欲和源自自身热爱的内驱力的结合。拥有好奇心的人善于提出问题、解决问题，而且提出问题比解决问题更彰显好奇心。寻找真相是困难的，但有好奇心的人就会爱折腾、爱琢磨，不满足于自己的已有经验，不断地问为什么，寻找现象和数据之间的底层联系，把事情想透彻。不能因为在行业待久了，就对创新的事物不管不问，甚至觉得创新的事物不靠谱。好奇心让人保持平和的心态，先尝试着接受，再去理解和判断。

第二，这种好奇心不受短期利益的影响，不受金钱驱动。不能仅研究或涉足带来短期快速回报的项目，而忽视自己长期热爱的领域。换句话说，每个人都应该从自己真正的好奇心出发，而不能被表象所迷惑，以为那是自己想追求的东西，有的时候人们喜欢追风口， 但尤其需要谨记这一点：人多的地方你别去。 

第三，好奇心不受好胜心或者战胜他人的成就感所驱动，不是为了当第一把别人比下去，也不是为了战胜市场。邓普顿基金集团创始人约翰·邓普顿有句名言：“战胜市场是一个很富有野心的目标，但追求它的时候要小心为上。”我们无法验证市场是对的，但也绝不敢说市场是错的，没有对市场的主观评价，也不去做简单的对比。 

理性的好奇强调依靠研究，而不是依靠垄断性资源或者运气，虽然那样会给人一种有捷径的错觉，但这些捷径或虚无的错觉都会误导认知。

中国传统的教育模式是讲堂式教育，而如今越来越强调思辨式教育——不是一味地服从权威，或者按大多数人的看法行事，而是根据自己的研究和思考得到答案。只有通过独立思考，不断客观地拷问自己是否尊重了事实和常识，形成的见识才是自己的。而且，这样的见识会转化成智慧，并会随着时间复合式增长。

市场在一段时间里与你的看法不同，或者许多人的观点与你的不同，并不意味着你的观点是错误的。独立判断意味着对市场保持冷静的思考，不要轻易妥协。很多时候，妥协会产生一个“坡”，你从“坡”上慢慢下来，刚开始没有感觉，但下得越多速度越快，等你意识到的时候，往往已经很难改变了。独立性就是不盲目，不轻易受别人观点的影响，充分考虑各种可能性后，基于严谨的逻辑独立做出判断。

我相信，如果你要创新，必须愿意长时间被误解。你必须采取一个非共识但正确的观点， 才能战胜竞争对手。 

独立思考更加强调不能盲目信任自己的经验，不能有认知上的偏见。许多投资人喜欢复盘，总结过去的得失经验，但习惯用很老旧的经验去解决当前的问题，或者干脆简单机械地套用刚刚积攒的经验去解决新出现的问题，这其实比不积累经验还要可怕。很多人会避免犯相同的错误，但如果只是盲目信从经验，就有可能不断地犯新错误。许多人相信历史会周期往复，但也有人觉得这次会不一样，其实**读历史的目的**并不是一劳永逸地知道该怎么办，而是为了总结出规律，因此我们需要看到事情的多样性、丰富性。每次判断都是崭新的，都应该向前看。**要把历史当作一种知识储备和情景训练，当作抵御重大风险的压舱石，而不是保你百战百胜的万能药**。

首先，长期持有只是结果，而不是目的。长期持有只是价值投资的某种外在表现形式，有些价值的实现需要时间的积累，有些价值的实现只需要环境的重大变化，所以不能说长期持有就是价值投资，非长期持有就不是价值投资。其次，购买低估值的股票并不是价值投资回报的持续来源，企业持续创造价值才是。特别是在当前的市场情况下，很难找到账面价值低于内在价值的投资标的。

思考和逻辑推演过程的重要性远远大于你所得到的结论。结论固然很重要，但微判断是载体，是一个人形成结论的过程。把许多微判断融入逻辑推演的分析框架中，才真正显出功力。

## 避开价值投资中的陷阱

- 陷阱一：价值陷阱。价值陷阱的本质是企业利润的不可持续性或者说不可预知性，投资人需要看更长远的周期或更大的格局，才能够识别并避免价值陷阱。
- 陷阱二：成长陷阱。避开成长陷阱的办法就是保持平常心，坚持第一性原理，不要为了发现成长股而定义成长股，否则很容易被“得道升天”的侥幸所迷惑。
- 陷阱三：风险陷阱。要学会宽容自己的错误，同时把每一次错误变成学习经验。正所谓“君子不立危墙之下”，规避风险陷阱的办法之一就是本杰明·格雷厄姆所说的**寻求安全边际**。
- 陷阱四：信息陷阱。信息陷阱的本质就是信息本身不会告诉你立场或观点，更不会告诉你它有多重要，你所观察的角度决定了你看待信息的方式。

**避开价值投资的陷阱**，归根结底是保持理性，保持理性的诚实，在没有充分地研究之前， 在思维模式尚未得到检验之前，在没有把风险管理好之前，平衡好自信和谦虚的心态，保持积极的克制和勇敢的主动。

## 价值投资无关对错，只是选择

投资之道，万千法门。坚持何种投资理念，都不能以名门正派自居，更不能自认高手包打天下。武林之大，但凡修得暗镖神剑者，亦可独步江湖。所以门派无尊贵，只有适合不适合。 

坚持一种投资方法的关键在于**你要遵守一套游戏规则**，就像音乐家的内心要有浑然的交响，诗人的内心要有和谐的意境，军人的内心要有统一的信念。如果脑子里有不同的标尺或者不同的声音，就会造成自我意识的混乱。只要坚持的基础原则相同，你就可以无所限制地表达，表达方式可以很丰富。所以，我们并不是以价值投资作为唯一的赚钱方法，而是**把价值投资作为一种信念，一种让心灵获得安宁的工作和生活方式**。

## 交给我管的钱， 就一定把它守护好

这个世界上唯有两样东西能让我们的心灵感到深深的震撼，一是我们头上灿烂的星空，一是我们内心崇高的道德法则。 

价值投资者的自我修养，就是在长期追求内心宁静的过程中，坚持有所为有所不为；在道德自律和纪律约束中，重复反思，尊重常识，认知自我。所谓“初有决定不移之志，中有勇猛精进之心，末有坚贞永固之力”，正是长期主义的写照。

总结：  
- 价值投资不必依靠天才，只需依靠正确的思维模式，并控制自己的情绪。
好奇心不受好胜心或者战胜他人的成就感所驱动，不是为了当第一把别人比下去， 也不是为了战胜市场。
- 信念有时比处境更加重要，你的格局观决定了你的生存环境，也决定了你的投资机会。
- 方法论本质上并无高低之分，只是天性的自知、自省与自洽。
- 选择投资方式就是选择自己的生活方式，**出发点是你自己的内心，选择的是能够让你有幸福感的东西**。

# 价值投资的创新框架

## 与伟大格局观者同行

凡盛衰，在格局。格局大，则虽远亦至；格局小，则虽近亦阻。 

## 拥有长期主义理念

运气总是飘忽不定的，拥有长期主义理念的创业者，本质上是具有长线思维的战略家。他们往往选择默默耕耘，不去向外界证明什么，而是把自己的事情做好。事情做得久了，就成了他的核心能力。

## 拥有对行业的深刻洞察力

要求很强的终身学习和研究的能力，把学习和研究变成一种生活方式和工作习惯，更需要一种穷根究底的态度。

## 拥有专注的执行力

匠人精神不是把大事做好，而是把小事做到极致，相信“小我有力量”。

## 拥有超强的同理心

同理心是一种发自内心的尊重和关爱。拥有同理心的人既能够认可他人的成功， 也能够理解他人的失败；既能够雪中送炭，也能够锦上添花；不刻意嘘寒问暖， 不虚以敷衍、曲意逢迎；能置身于他人的处境中，体会他人的情绪和想法，共情他人的立场和感受。 

人虽然能够做他所想做的，但不能要他所想要的。同理心会带给你一种宽容的力量，对他人和自己的宽容，免于过度气馁或者对他人苛责，这会让你更好地成就自己。

## 选择与谁同行，比要去的远方更重要

自己必须是个好人，要始终对自己保持极高的道德要求。在做个好人的前提之下，要相信自己，高看自己，对自己有信心。只要秉持正确的价值观和道德观，就能够赢得长期而关键的信任。 

没有一定要做的生意，但有一定要帮的朋友。

# 持续创造价值的卓越组织

## 时间价值管理：做一名超级CEO

## 打造文化：追求内心的宁静

## 绽放人才：和靠谱的人做有意思的事

## 激活组织：创建好的小生态系统

# 产业变革中的价值投资

科技不是颠覆的力量，而是一种和谐再造的力量。

## 哑铃理论：让科技成为和谐再造的力量

## 突破生命科学：研发与创新

以**药明康德**为例，这家中国规模领先、全球排名前列的小分子医药研发服务企业，主营业务包括外包研发和外包生产／外包生产研发（CMO/CDMO）业务两大类别，在药物发现、临床前研究、临床研究及生产方面均有业务布局，通过全球26个研发基地和分支机构为超过3000家客户提供各类新药的研发、生产及配套服务。 

**凯莱英**，它是一家全球领先的、服务于新药研发和生产的一站式综合服务商。其核心业务涵盖了从新药临床早期到商业化的定制生产和技术开发等服务，与排在全球前15名的跨国制药企业中的11家建立了长期合作，核心客户包括默沙东、百时美施贵宝、诺华、艾伯维和辉瑞等。凯莱英凭借其高度专注和重视研发的经营理念， 积累了非常前沿的技术能力和丰富的制药工艺。 

投资了国内最大的眼科连锁医疗机构——**爱尔眼科**，深耕第三方医学检验及病理诊断业务10余年的创新企业——**金域医学**，以及国内领先的辅助生殖综合服务商——**锦欣生殖**。 在医疗器械领域，中国产业的快速发展也才刚刚开始，涌现了许多致力于高值器械和微创医疗的创新型企业。高瓴投资了布局最广的医疗器械平台型企业——**迈瑞医疗**和**上海微创**，还支持了专注于骨科、心血管微创、运动医学等医疗科技领域的创新企业——**凯利泰**，国内骨科关节植入物市场龙头厂商——**爱康医疗**，以及**沛嘉医疗**、**微创心通**、**启明医疗**等具有内生
增长潜能的企业，就是希望源自中国创新的企业，能够真正满足中国患者的需求。

对于中国药企来说，“从仿到创”不是信手拈来，无法一蹴而就。关键时点和关键变化不仅在于外界环境，核心还在于专注研发、专注创新。毕竟仿制药行业是靠强销售驱动的，做仿制药的核心不在于研发人员，而在于医药代表。而创新药行业是靠强创新驱动的，具有投入高、周期长、风险大的特点。成药性是创新药的独木桥， 也是考验投资人的关键要素。 

**百济神州**令人印象深刻。作为一家根植于中国的全球性商业化生物制药公司， 百济神州致力于成为分子靶向药和肿瘤免疫药物研发领域以及商业化创新领域的全球领导者，是首家在中国和全球范围同步开展注册型临床试验的创新药企，目前已在五大洲开展了临床试验，也是国内首家在纳斯达克和港交所双重上市的生物制药公司。立足于自身扎实的生物医药研发功底，百济神州现已成为一家涵盖研究、临床开发、生产及商业化的全面发展型企业。

坚持**研究驱动、以人为本**的价值投资一旦和生命科学领域相结合，就不仅仅是一种方法论，更是一种价值观，观照生命健康，关注人类社会的长远发展。

## 拥抱消费转型：升级与细分

引入大数据团队，把线上线下积累的消费者数据进一步收集加工，并通过线上电商数据、地图数据，建立线下选址模型，选择最具潜力、最有活力的门店地址和销售策略，提升门店拓展效率。作为一家零食店铺，良品铺子从上游的原料采购、供应链管理、产品研发，到门店销售、品牌营销，不断吃透整个价值链条，从而像互联网企业一样，做到零售领域的“千人千面”。这背后不仅需要超强的大数据、供应链管理能力，更需要对新零售本质的理解。

在消费转型的未来，线上和线下不再有明显的区隔，后台的数据与前台的交互时刻更新，上游和下游连为一体，物质和精神彼此交融，品牌丰富而温暖，产品新奇而繁多，但不同消费者却能够各取所需，在所想即所得、所得即所需的消费体验中，寻找与理想生活的共鸣。

## 闯入智能时代：产业互联网

在产业互联网时代，科技与产业快速融合、重构，这决定了价值投资有望作为技术创新和实体经济之间的催化剂，弥合技术基础设施之间的鸿沟，这也是时代赋予“价值投资服务实体经济”的新使命。

## 价值创造赋能路线图

- 在新消费的概念中，产品及其品牌包含了在服务过程中与消费者沟通的全方位要求，换句话说，零售即服务，内容即商品，所见即所得，物质组成的产品力和文化组成的品牌力共同成为理解消费新趋势的复合视角。
- 新零售的实现方式，就是用更加细分的场景满足不断变化的需求，好的消费场景是打造品牌力的关键。
- 数字科技化赋能是在飞行中换发动机，不会改变传统企业的行业属性，不是“停业整顿”，也不是为了创新而创新，必须直接为业务带来增量。
- 世界上本没有科技企业和传统企业的分野，优秀的企业总会及时、有效地使用一切先进生产要素来提高运营效率，从而实现可持续增长。

# 价值投资的实践探索

## 创新新起点：实体经济巨头的价值重估

## 激发新动能，重仓中国制造

格力电器的股权转让最终顺利完成，在这之中我们最大的体会就是**要尊重企业和企业家精神，尊重每一位企业员工的创造力**。当然，我们后面还有更长的路要走，包括发挥长期资本的优势、利用全球研究以及帮助实体经济转型升级的经验，帮助格力电器引入更多的战略资源，进一步改善公司治理，实现战略发展的重新定位、核心技术的突破以及国际化、多元化发展等。以数字化转型为标志的产业变革，无法一蹴而就，必须局部突破，小步快跑，积累数字化转型的经验和信心，逐步实现产业的华丽升级。

## 开拓新世界：think big, thing long

从商业物种的创新，到产业的快速迭代，从早期投资、成长期投资到并购投资，从海外模式的中国实践到中国模式的海外拓展，价值投资正在经历更多发展和变化。这其中的核心没有变，就是是否在为产业发展和社会进步创造长期价值，是否在坚持长期主义，是否在做时间的朋友。

- 价值投资者只有在长远问题上想清楚，在行业塑造、价值创造的维度上想清楚， 才能经得起时间的考验。
- 一个商业物种的产生起源于它所处的时代和环境，其积累的生产能力、供应链效率和品牌价值，是对那个年代最完美的诠释，堪称经典，而经典的价值不可能瞬间土崩瓦解， 也不会凭空消失。
- 科技不是科技企业的专利，传统制造业加上科技，将从产业端改造整个商业系统， 适应不断进化的商业环境。
- 并购投资的出发点并不是追求投资规模或者单纯的投资收益，更关键的，是在原有商业模式创新进入阶段性瓶颈的情况下，判断科技赋能能否成为驱动产业升级的新价值所在，能否通过科技创新对现有商业模式进行精细化打磨，通过引入新的资源改善被并购公司的长远状况。
- 真正的“重仓中国”，就是要帮助中国制造业更好更快地实现转型升级，真正地在产业中提升数字化、科技化、信息化水平，帮助中国制造业占据价值链的最高端。

# 永远追求丰富而有意的人生

> 教育是对人生最重要、 最明智的投资。

一是“守正用奇”，就是要在坚守“正道”的基础上激发创新；第二是“弱水三千，但取一瓢”，就是一个人要在有限的天赋里做好自己最擅长的那部分；第三是“桃李不言，下自成蹊”，就是指只要好好做自己的事，成功自会找上门来。

虽然有时候，也许有人不靠诚实也能成功，但这种成功不但不持久，还有可能会“搬起石头砸到自己的脚”。在知识和智力上的独立也是非常重要的，能否形成独立的思辨能力实际上是决定年轻人能坚持走多远的基石。如果一个人同时拥有理性的好奇心、诚实的品质、思考的独立性，再加上一些同理心，并且有长期奋斗的心态，那么能否获得成功就只剩下运气和大数法则的问题。或者说，一遍一遍地做让你有激情的事，并且乐在其中，那么成功只是时间问题。

强大的学习能力和对事物的敏锐洞察力，是一个人能力的护城河。所以一个人要学会坚守自己的理想，珍惜自己短期内没有被外界看破的窗口机会，把护城河架构好，形成持续学习和创新的能力。

## 长期主义的人才观

当然，“梦想有多大，舞台就有多大”，让每个人能走得更远的，归根结底还是自我驱动力和自我学习能力，是对真理的热爱和追求，是持续解决社会痛点的使命感。只有这样，才能不断吸收、消化平台和实践提供的输入，不断提高自己思考的维度，与公司一起创造更大的价值的同时，实现个人价值的不断提升。

## 成长型的人才培养机制

著名作家汪曾祺说，一个人的口味要宽一点、杂一点，“南甜北咸东辣西酸”，都去尝尝。对食物如此，对文化也应该这样。实际上，这样宽一点的口味，用在对人才的要求上，也是完全适用的。我们要培养能学会玩、十八般武艺样样精通、 拥有跨学科思维的“多栖明星”。

## 教育和人才是永不退出的投资

**为善最乐，是不求人知。**高瓴坚持“桃李不言，下自成蹊”的投资哲学，就是此意。在更宏大的世界观里，价值投资可以发挥更大的作用，可以做创新资本与赋能资本，但首先应该做“良善资本”，通过在教育、科学、扶贫等公益领域的投入，让更多人、更基础的力量以更包容的方式塑造未来。

中国的创新如果只靠商业模式的创新，总有一天会走到头。再往后，国家竞争力的提升就需要把基础科学打得更扎实。所以，无论是倡议设立未来科学大奖，还是支持西湖大学，本质上都是要帮助科学家做一些长远来看有意义的事。因此，作为一家坚持长期主义的投资机构，我们有责任帮助孵化、连接并转化基础研究和原始创新的成果，帮助更多投资人理解和掌握价值投资理念背后的精神，将科技进步、创业创新和价值投资连接起来，成为推动社会进步的基础力量。

**教育和人才，可能是最长远的投资主题**，永远不需要退出。当教育驱动人才和社会蓬勃发展、不断创造价值的时候，在更宏大的格局观里，投资人能够发现更多有意义的事情，这也是最大化创造价值的超长期主义。

- 对于有潜质、价值观一致的员工，我们奉行长期主义，不着急，慢慢来，给予其充足的成长时间。
- 教育是一个很讲究情感关怀和激励的领域，越是处于一个“机器横行”的人工智能时代，我们就越是呼唤人性中独特的同理心和情感互动等真正有温度的东西。
- 未来的构建需要无尽的想象力和踏实的执行力，这两种力量汇聚在一起就是创新，而创新的核心正是人才。

## 做时间的朋友

人的一生，可以选择很多种生活方式。中国古代传统思想讲求“穷则独善其身，达则兼济天下”。在我看来，如果穷、达之间仍然可以创造价值的话， 一定更有意义。与成功相比，不断成长的历程更令人难忘。人们在社会中接受历练、选择挑战、不断摸索，就像科学家在自然科学领域探索一样，发现价值和创造价值都意义非凡。

我也常常思考**个人与时代的关系**。与原始社会的幸存者往往依赖于强健的体魄，封建社会的佼佼者往往仰仗家世、血缘，偶尔才有人通过努力考取功名不同，生于现代社会的我们遇到了最好的时代，可以通过接受教育、学习知识和探索创新改变自己的命运。我是教育改变命运的典型。河南的人口基数大，人们努力追求更美好的生活，这恰恰是中国的一个缩影。在这个缩影中，我通过接受良好的教育考入好的大学，在国内好的企业工作，又去美国留学实践，进而选择投资事业。正因如此，感恩是我永远的心灵归宿。有很多人比我们聪明、勤奋，只是他们生活中没有这样或那样的机遇，或者现实容不得他们误打误撞。所以，任何处境下都不能高己卑人。有的时候，遭受过苦难，才能理解别人的难处。苏格拉底说过，未经审视的人生不值得过。

思考至此，我清晰地发现，在长期主义的范畴中，做公益和做价值投资殊途同归。任何财富都是时代所赐，因此要善用这些财富，其中的关键是“运用之妙，存乎一心”，保持内心的平衡与平静，打通“任督二脉”，最终重剑无锋。我们所做的投资，不见得是赚钱最快的方式，也不见得是赚钱最多的路径，但这是让我们获得心灵宁静的道路。

**“尚未佩妥剑，转眼便江湖。愿历尽千帆，归来仍少年。”**从事投资多年以后，我越发觉得大道至简，无论是面对创业者、消费者还是出资人，我所坚持的都从未改变：追求真理，追求价值创造。天地不言，四时行焉；时光不语，真心明鉴。古人说：“人生天地间，忽如远行客。”我们希望在长期主义的实践历程中，寻万物流转，觅进退有章，做时间的朋友，回归内心的从容。

## 将绽放进行到底

## 选择做时间的朋友

在人生的道路上，**选择与谁同行，比要去的远方更重要**。今年毕业的同学，你们现在就好好看看身边的人吧。他们或许是你的老师、好友，或许是你的挚爱，或许你们之间交集并不多，甚至互不相识，或许你们以后会经常见面，或许从此天各一方、再会无期，但无论任何时候，无论你们身在何方，人大永远会是将你们紧密联系在一起的一条纽带。我很幸运，通过这条纽带认识了很多靠谱的人，和他们一起做了很多有意思的事情。

## 有一条解决当今很多现实问题的根本途径

## 用“科技+”做正和游戏

## 人工智能是对话未来的语言

## 这是一门需要用一生去研习的必修课

## 论一个投资者的自我修养

**能否诚实地面对自己，是作为投资人的第一重考验**，这不仅对于年轻的学生来说是考验，而且对于在事业上非常成功的人来说更是巨大的考验。如果听到同事的称赞就扬扬得意、沾沾自喜，那么接下来你就离失败不远了；如果所有人都和你说你真正地掌握了真理，并且你真的这样相信了，那么你也离失败不远了。评判一个投资人首先要看他能否诚实地、客观地面对自己，尤其是诚实地面对自己的失败。有人跟我说，“我只是对我的出资人吹吹牛，要不然大家都不投资我了”。

## 以价值投资理念优化市场资源配置

## "科技创新2.0"助力构建经济新格局

## 大学筹资核心在于广泛性和永续性

## 致敬雪山之魂

## "守正用奇"，论耶鲁捐赠基金的投资哲学

## 心灵宁静，"延迟满足"

天下武林，林林总总。名门正宗如少林武当，诚然名扬天下，而武林之大，但凡修得暗镖神剑者，亦可独步江湖。所以门派无尊贵，只有适合不适合。本序开宗明义：即使最成功的投资人，也要心胸坦荡，认识到自我局限，不可以名门正宗自居，须认识到获得真理是一个学无止境、永远追求的过程。

要有个好心境、好家庭、好身体。投资这项事业进行到最后，反映的是你个人的真实性情和价值观。健康的环境和心情是长期修行的结果。成功诚然需要运气和际遇的配合，但能否幸福地去做投资，则掌握在你自己手里。

## 叙事：理解过去与未来

改变命运唯一的策略是你要变成终身学习者，未来世界将不再需要单一的技能型人才，而是需要具备完善的知识结构、极强逻辑思考力和高感知力的复合型人才。优秀的人往往通过阅读建立足够强大的抽象思维能力，获得异于众人的思考和整合能力。未来，将属于终身学习者！而阅读必定和终身学习形影不离。
很多人读书，追求的是干货，寻求的是立刻行之有效的解决方案。其实这是一种留在舒适区的阅读方法。在这个充满不确定性的年代，答案不会简单地出现在书里，因为生活根本就没有标准确切的答案，你也不能期望过去的经验能解决未来的问题。

泛读、精读、通读

何止于米，相期于茶

有时去治愈，常常去帮助，总是去安慰

```{js, echo=FALSE}
$('.title').css('color', 'red')
$('.title').css('font-family', 'Times New Roman')
```

```{css, echo=FALSE}
* {
    # font-size: 17px !important;
    font-family: "Times New Roman" !important;
    # color: rgb(0 0	0)
}
::selection {
   # background: rgb(135 206 255);
}
```

```{css, echo=FALSE}
h2 {
    font-size: 21px !important;
    font-family: "Times New Roman" !important;
    color: rgb(	255 140 0)
}
h1 {
    font-size: 24px !important;
    font-family: "Times New Roman" !important;
    color: rgb(	255 0 0)
}
::selection {
   # background: rgb(135 206 255);
}
```

```{r,echo=FALSE}
library(bubblyr)
bubblyr::bubbly(theme = "warmup")
# bubblyr::bubbly(theme = "rladies")
```
